---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beproject.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "beproject.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "beproject.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "beproject.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secret-kv
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-kv
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-kv
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret-kv
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-kv
                  key: REDIS_PASSWORD
          livenessProbe:
            httpGet:
              path: /app/actuator/health/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /app/actuator/health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 60
