name: App buid

on:
  push:
    branches:
      - dev
      - test
      - prod
env:
  BUILD_NAME: "${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}"
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Set FULL_BUILD_NAME
        id: extract-full-build-name
        run: |
          FULL_BUILD_NAME=$BUILD_NAME:${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}
          echo "FULL_BUILD_NAME=$FULL_BUILD_NAME" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests && build
        run: mvn --batch-mode clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $FULL_BUILD_NAME .

      - name: Push Docker image
        run: docker push $FULL_BUILD_NAME

      - name: Update Chart.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/beproject/Chart.yaml'
          changes: |
            {
              "version": "${{ github.sha }}",
              "version": "1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}"
            }
          commitChange: false

      - name: Update Values.yaml dev/test
        if: steps.extract_branch.outputs.branch != 'prod'
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/beproject/values.yaml'
          changes: |
            {
              "image.repository": "${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}",
              "image.tag": "${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}",
              "namespace": "${{ steps.extract_branch.outputs.branch }}",
              "ingress.host": "${{ steps.extract_branch.outputs.branch }}${{ vars.URL_POSTFIX }}"
            }
          commitChange: false

      - name: Update Values.yaml prod
        if: steps.extract_branch.outputs.branch == 'prod'
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm/beproject/values.yaml'
          changes: |
            {
              "image.repository": "${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.PROJECT_NAME }}",
              "image.tag": "${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}",
              "namespace": "${{ steps.extract_branch.outputs.branch }}",
              "ingress.host": "${{ steps.extract_branch.outputs.branch }}${{ vars.URL_POSTFIX }}",
              "replicaCount": "${{ vars.PROD_REPLICA_COUNT }}"
            }
          commitChange: false

      - name: Set up global config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone helm repository
        run: |
          git clone https://github.com/ArthurF-java/helm-be.git
#          helm package helm/beproject -d ./helm-be/${{ steps.extract_branch.outputs.branch }}

      - name: Push to helm repository with retries
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: |
                cd helm-be
                git fetch
                git pull
                git status
                git reset --hard origin/main
                echo 'second status ++++++++++++++++++++++++++'
                git status
                helm package ../helm/beproject -d ./${{ steps.extract_branch.outputs.branch }}
                echo "version: 1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}"
                echo 'check dev folder'
                ls dev/
                helm repo index --url "https://arthurf-java.github.io/helm-be/" --merge index.yaml .
                git add --all
                git commit -m "${{ steps.extract_branch.outputs.branch }}"
                git push https://${{ secrets.TOKEN_GITHUB }}@github.com/arthurf-java/helm-be.git main

#      - name: Push to helm repository
#        run: |
#          cd helm-be
#          git fetch
#          git pull
#          helm repo index --url "https://arthurf-java.github.io/helm-be/" --merge index.yaml .
#          git add --all
#          git commit -m "${{ steps.extract_branch.outputs.branch }}"
#          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/arthurf-java/helm-be.git main
#          cd ..

      - name: Ping helm repo until it returns 200
        run: |
          url="${{ vars.HELM_REPO_URL }}${{ steps.extract_branch.outputs.branch }}/beproject-1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}.tgz"
          max_attempts=40
          attempt=1
          sleep_duration=5

          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt: Pinging $url..."
            response_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")

            if [ "$response_code" -eq 200 ]; then
              echo "Success: Received HTTP 200!"
              exit 0
            else
              echo "Failed: Received HTTP $response_code. Retrying in $sleep_duration seconds..."
              sleep $sleep_duration
              attempt=$((attempt + 1))
            fi
          done

          echo "Error: Max attempts reached. Exiting."
          exit 1

      - name: clone ArgoCD
        run: |
          ls
          git clone https://github.com/ArthurF-java/argo-cd.git

      - name: Update ArgoCD application.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'argo-cd/${{ steps.extract_branch.outputs.branch }}/application.yaml'
          changes: |
            {
              "spec.source.targetRevision": "1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}"
            }
          commitChange: false

      - name: Pust to ArgoCD repository
        run: |
          cd argo-cd
          git add --all
          git commit -m "${{ steps.extract_branch.outputs.branch }}"
          git fetch
          git pull
          git push https://${{ secrets.TOKEN_GITHUB }}@github.com/arthurf-java/argo-cd.git main

      - name: Pust to ArgoCD repository with retries
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: |
                cd argo-cd
                git add --all
                git commit -m "${{ steps.extract_branch.outputs.branch }}"
                git fetch
                git pull
                git push https://${{ secrets.TOKEN_GITHUB }}@github.com/arthurf-java/argo-cd.git main

      - name: Slack Notification Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: afon-check
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: 'Deploy be is done for image 1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}'
          SLACK_USERNAME: fonichkin
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: afon-check
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: 'Deploy be is failed for image 1-${{ steps.extract_branch.outputs.branch }}-${{ github.sha }}'
          SLACK_USERNAME: fonichkin
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}